<?php
/**
 * Copyright © Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * See COPYING.txt for license details.
 */
?>
<?php $collection = $block->getCollection() ?>
<?php if ($collection->getSize()) : ?>
    <div class="faonni-socialprovider">
        <div class="block-title"><?= $block->escapeHtml(__('Connect with Social')) ?></div>
        <?php foreach ($collection as $provider) : ?>
            <a href="<?= $block->escapeHtml($provider->getUrl()) ?>"
                class="provider provider-<?= $block->escapeHtml($provider->getId()) ?>" 
                data-width="<?= $block->escapeHtml($provider->getWidth()) ?>" 
                data-height="<?= $block->escapeHtml($provider->getHeight()) ?>">
                <?= $block->escapeHtml($provider->getTitle()) ?>
            </a>
        <?php endforeach ?>
    </div>
    <?php if ($block->isPopupMode()) : ?>
        <script type="text/x-magento-init">
            {".provider": {"faonni/sociallogin": {}}}
        </script>
    <?php endif ?>
<?php endif ?>